Feat/primary community
BloomMate/BloomMate-FE pull request #46
Opened 2023-11-13 16:11 UTC by nyeonaa

## 작업 유형 ✨

- [ ] 기능 추가
- [x] 버그 수정
- [ ] 리팩토링
- [ ] 문서 업데이트
- [ ] 기타(설명 필요)

## 작업 배경 사항 🚀

(작업한 내용에 대한 배경 사항)

## 변경 사항 📝

- (변경된 파일 또는 디렉토리 리스트)

## 변경 전 스크린샷 📸 (Optional)

(변경 이전의 스크린샷)

## 변경 후 스크린샷 📸 (Optional)

(변경 이후의 스크린샷)

## 기타 참고 사항 🎈

(기타 리뷰어에게 전달할 사항)

2023-11-16 16:08 UTC, DonghyunKim98 requested changes

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/hooks/get-question-detail/get-question-detail.hook.ts
> +};
- `get-plant-detail-query` 를 보신다면 useQuery 의 key 값을 배열로 설정하여 query 를 넘길 수 있습니다.

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/hooks/get-question-detail/get-question-detail.hook.ts
> +};
- 그리고 API 를 참고하니
```
useQuery<QuestionDetailResponse>([`/community/question_detail`, {question_id : id}]);
```

로 가야할듯 합니다.

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/hooks/get-question-list/get-question-list-query.hook.ts
> +  return useQuery<QuestionListResponse>('/community/?page_size=10');
- API 문서를 정확히 따라주세요.

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/components/primary-community-tab-label/primary-community-tab-label.component.tsx
> +    style={{ marginBottom: 16 }}>
- marginBottom 이 반드시 필요한가요?
- 필요한 스크린샷 부탁드립니다.

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/primary-community.screen.tsx
> +        onPressExit={() => navigation.goBack()}
- `handlePressExit` 으로 빼주세요

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-article/primary-article-webview.screen.tsx
> +    }, []);
- `useBackHandler` 이용해주세요.

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/components/primary-community-qna-list-item.component.tsx
> +              height: 136,
- height 값이 나오면 의심하게 됩니다.... padding 을 이용할 수 없었는지요.
- 아니면 minHeight 이거나
- 고정 height 여야 했나요?

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-detail/qna-detail-answer/qna-detail-answer.tsx
> +                style={{ aspectRatio: 50 / 50, minWidth: 50 }}
- aspectRatio : 1 로 이해하기 쉽게 바꿔주세요

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-post/primary-community-qna-post-content/components/qna-post-content-content/qna-post-content.component.tsx
> +        multiline={true}
- multiline 만 줘도 됩니다. (true 의 경우에는)

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-post/primary-community-qna-post-content/primary-community-qna-post-content.module.tsx
> +      <Box>
- 상단을 Box 로 감싼 이유는?

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-post/primary-community-qna-post-footer/hooks/post-community-qna.hook.ts
> +        return queryClient.invalidateQueries('/community/?page_size=10');
- 이것도 추후에 수정이 필요합니다~

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-post/primary-community-qna-post-footer/primary-community-qna-post-footer.module.tsx
> +          style={{ marginTop: 16 }}
- 퍼블리싱이 매우 부자연스러워 보여요.
- 회원가입에서도 이렇게 했나요?

2023-11-16 16:08 UTC, DonghyunKim98 commented on src/screens/primary/primary-community/screen/primary-community-qna/primary-community-qna-detail.screen.tsx
> +      console.log(data);
- 나중에 지워주세요

2023-11-17 05:12 UTC, nyeonaa commented on src/screens/primary/primary-community/components/primary-community-tab-label/primary-community-tab-label.component.tsx
> +    style={{ marginBottom: 16 }}>
이거 그 식물리스트 성장중/수확완료랑 똑같은건데용 어차피 디자인 바뀌어서 바뀌어야 되니까 그냥 냅둘게여!!

2023-11-17 05:17 UTC, nyeonaa commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/components/primary-community-qna-list-item.component.tsx
> +              height: 136,
이거 질의응답 리스트의 질문인데 피그마에서 고정 height 사용하라고 되어 있어 사용했습니다! 상세페이지에서는 고정 height 아닙니당

2023-11-17 05:19 UTC, nyeonaa commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-post/primary-community-qna-post-content/primary-community-qna-post-content.module.tsx
> +      <Box>
왜 그랬지... 지웠습니다 ㅋㅋㅋ ㅠㅠ

2023-11-17 05:20 UTC, nyeonaa commented on src/screens/primary/primary-community/screen/primary-community-qna/modules/primary-community-qna-post/primary-community-qna-post-footer/primary-community-qna-post-footer.module.tsx
> +          style={{ marginTop: 16 }}
이거 여쭤보고 싶은 게 내용 크기가 커서 회원가입 때나 로그인 떄처럼 하면 질문하기 버튼이 내용 박스를 가려버리더라고요! 그래서 어떻게 하는 게 맞는지 궁금합니다!!

2023-11-18 09:55 UTC, DonghyunKim98 approved these changes

2023-11-18 09:55 UTC, merged